---
- name: Configure Nextcloud
  hosts: all

  tasks:

  - name: Set overwrite.cli.url
    ansible.builtin.replace:
      path: "{{nextcloud_data_directory}}/app_data/config/config.php"
      regexp: ".*overwrite.cli.url.*"
      replace: "  'overwrite.cli.url' => '{{protocol}}://{{host}}',"
    become: true

  - name: Set overwritehost
    ansible.builtin.replace:
      path: "{{nextcloud_data_directory}}/app_data/config/config.php"
      regexp: ".*overwritehost.*"
      replace: "  'overwritehost' => '{{host}}',"
    become: true
  
  - name: Set overwriteprotocol
    ansible.builtin.replace:
      path: "{{nextcloud_data_directory}}/app_data/config/config.php"
      regexp: ".*overwriteprotocol.*"
      replace: "  'overwriteprotocol' => '{{protocol}}',"
    become: true

  #TODO: Change trusted_domains?