---
- name: Install Nginx
  hosts: all
  vars:
    ssl_cert_path: /opt/nginx/ssl
    nginx_path: /opt/nginx
    domain: domain
    cockpit_internal_port: 9090 # Default, but can be configured

  tasks:

  - name: Check for Nginx service
    ansible.builtin.systemd:
      name: nginx
    ignore_errors: true
    register: service_status

  - name: Stop play if Nginx is installed
    meta: end_play
    when: service_status.status.LoadState == "loaded"

  # Generate self-signed certs

  - name: Create directory for certs
    ansible.builtin.file:
      path: "{{ ssl_cert_path }}"
      state: directory
    become: true

  - name: Generate private key and self-signed certificate
    ansible.builtin.command: >
      openssl req -x509 -nodes -newkey rsa:2048
      -keyout {{ ssl_cert_path }}/{{ domain }}.key
      -out {{ ssl_cert_path }}/{{ domain }}.crt
      -days 365
      -subj "/CN={{ domain }}"
    args:
      creates: "{{ ssl_cert_path }}/{{ domain }}.crt"
    become: true

  # Installing Nginx

  - name: Create directories for configs
    ansible.builtin.file:
      path: "{{ nginx_path }}/config/conf.d"
      state: directory
    become: true

  - name: Create directories for logs
    ansible.builtin.file:
      path: "{{ nginx_logs }}/{{ item }}"
      state: directory
    loop:
        - cockpit
        - nextcloud
    become: true

  - name: Copy docker-compose config
    ansible.builtin.template:
      src: ./nginx/docker-compose.yml.j2
      dest: "{{ nginx_path }}/docker-compose.yml"
    become: true

  - name: Copy main nginx config
    ansible.builtin.copy:
      src: ./nginx/config/nginx.conf
      dest: "{{ nginx_path }}/config/nginx.conf"
    become: true

  - name: Copy other nginx configs
    ansible.builtin.template:
      src: "{{ item }}"
      dest: "{{ nginx_path }}/config/conf.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
    with_fileglob:
      - ./nginx/config/conf.d/*.j2
    become: true

  - name: Copy systemd config
    ansible.builtin.template:
      src: ./nginx/nginx.service.j2
      dest: /etc/systemd/system/nginx.service
    become: true

  - name: Enable Nginx
    ansible.builtin.systemd_service:
      name: nginx
      state: started
      enabled: true
      daemon_reload: true
    become: true
