---
- name: Install Cockpit
  hosts: all
  vars:
    cockpit_port: 9090 # Default, but can be configured

  tasks:
  - name: Ensure that Cockpit is installed
    ansible.builtin.package:
      name: cockpit
      state: present
    become: true

  - name: Ensure that the config directory exists
    ansible.builtin.file:
      path: /etc/systemd/system/cockpit.socket.d
      state: directory
    become: true

  - name: Configure port
    ansible.builtin.copy:
      dest: /etc/systemd/system/cockpit.socket.d/listen.conf
      content: |
        [Socket]
        ListenStream=
        ListenStream={{ cockpit_port }}
    become: true

  - name: Configure redirect
    ansible.builtin.copy:
      dest: /etc/cockpit/cockpit.conf
      content: |
        [WebService]
        Origins = https://host.docker.internal:{{ cockpit_port }} wss://host.docker.internal:{{ cockpit_port }}
        ProtocolHeader = X-Forwarded-Proto
    become: true

  - name: Restart Cockpit
    ansible.builtin.systemd_service:
      name: cockpit.socket
      state: restarted
      daemon_reload: true
    become: true
