---
#TODO: Use another installation method

- name: Install Docker
  hosts: all

  tasks:
  
  - name: Check for docker binary
    ansible.builtin.command: which docker
    changed_when: false
    failed_when: false
    register: docker_check

  - name: Stop play if Docker is installed
    meta: end_play
    when: docker_check.rc == 0

  # Installation

  - name: Generate UUID
    command: python3 -c "import uuid; print(uuid.uuid4())"
    register: generated_uuid
    when: docker_check.rc != 0

  - name: Create a directory
    ansible.builtin.file:
      path: /tmp/{{generated_uuid.stdout}}
      state: directory
    when: docker_check.rc != 0

  - name: Download docker installation script
    ansible.builtin.get_url:
      url: https://get.docker.com
      dest: /tmp/{{generated_uuid.stdout}}/get-docker.sh
      mode: '777'
    when: docker_check.rc != 0

  - name: Run installation script
    ansible.builtin.shell: /tmp/{{generated_uuid.stdout}}/get-docker.sh
    become: true
    when: docker_check.rc != 0

  - name: Remove installation script with directory
    ansible.builtin.file:
      path: /tmp/{{generated_uuid.stdout}}
      state: absent
    when: docker_check.rc != 0
