---
- name: Change ssh port
  hosts: all

  tasks:
  - name: Set port in config
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: 'Port '
      line: Port {{ new_port }}
    become: true

  - name: Restart ssh
    ansible.builtin.systemd_service:
      name: ssh
      state: restarted
      daemon_reload: true
    become: true
